### ISSUE TITLE
Wouldn't parse big-endian input

### ISSUE THREAD

**Issue by sheredom** [kusma/SPIR-V#1]
SPIR-V files can be either endian - you have to parse the magic to know what endian format the file is in.

Given that most platforms are little endian these days, I can see an argument for just bailing if the endian isn't correct, but thought I'd highlight this anyway.

**Comment by kusma** [comment]
Well, SPIR-V defines the in-memory representation to be a stream of words, not a stream of bytes. So I think for the parser itself i should be OK. But yeah, the code that loads the file from disk should detect endianess and swap if it's incorrect, good point.

**Comment by kusma** [comment]
OK, should be fixed in 4d91460363f98137a4d37bd381f7b76a13a02890, but I don't have a big-endian SPIR-V file to verify. Please let me know if it helps or not.
